// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: coffee.proto
package com.takusemba.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.WireEnum
import kotlin.Int
import kotlin.jvm.JvmField
import kotlin.jvm.JvmStatic

enum class Size(private val value: Int) : WireEnum {
  SMALL(0),

  MEDIUM(1),

  LARGE(2);

  override fun getValue(): Int = value

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<Size> = object : EnumAdapter<Size>(
      Size::class.java
    ) {
      override fun fromValue(value: Int): Size = Size.fromValue(value)
    }

    @JvmStatic
    fun fromValue(value: Int): Size = when (value) {
      0 -> SMALL
      1 -> MEDIUM
      2 -> LARGE
      else -> throw IllegalArgumentException("""Unexpected value: $value""")
    }
  }
}
