// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: google/protobuf/descriptor.proto
package com.google.protobuf

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.TagHandler
import com.squareup.wire.WireField
import com.squareup.wire.internal.Internal
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.collections.List
import kotlin.jvm.JvmField
import okio.ByteString

/**
 * The protocol compiler can output a FileDescriptorSet containing the .proto
 * files it parses.
 */
data class FileDescriptorSet(@field:WireField(tag = 1, adapter =
    "com.google.protobuf.FileDescriptorProto#ADAPTER") val file: List<FileDescriptorProto> =
    emptyList(), val unknownFields: ByteString = ByteString.EMPTY) : Message<FileDescriptorSet,
    FileDescriptorSet.Builder>(ADAPTER, unknownFields) {
  @Deprecated(
      message = "Shouldn't be used in Kotlin",
      level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Builder = Builder(this.copy())

  class Builder(private val message: FileDescriptorSet) : Message.Builder<FileDescriptorSet,
      Builder>() {
    override fun build(): FileDescriptorSet = message
  }

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<FileDescriptorSet> = object : ProtoAdapter<FileDescriptorSet>(
      FieldEncoding.LENGTH_DELIMITED, 
      FileDescriptorSet::class.java
    ) {
      override fun encodedSize(value: FileDescriptorSet): Int = 
        FileDescriptorProto.ADAPTER.asRepeated().encodedSizeWithTag(1, value.file) +
        value.unknownFields.size

      override fun encode(writer: ProtoWriter, value: FileDescriptorSet) {
        FileDescriptorProto.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.file)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): FileDescriptorSet {
        val file = mutableListOf<FileDescriptorProto>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> file.add(FileDescriptorProto.ADAPTER.decode(reader))
            else -> TagHandler.UNKNOWN_TAG
          }
        }
        return FileDescriptorSet(
          file = file,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: FileDescriptorSet): FileDescriptorSet? = value.copy(
        file = value.file.also { Internal.redactElements(it, FileDescriptorProto.ADAPTER) },
        unknownFields = ByteString.EMPTY
      )
    }
  }
}
